modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT-0"

[[mods]]
modId = "hexstuff"
version = "${version}"
displayName = "HexStuff"
logoFile = "icon.png"
authors = "Skye"
description = '''
Hex Casting Stuff
'''

[[dependencies.hexstuff]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexstuff]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexstuff]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexstuff]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
